DROP TABLE types
IF EXISTS;

DROP TABLE articles
IF EXISTS;

CREATE TABLE types (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE articles (
  id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name   VARCHAR(255),
  typeid BIGINT,
  PRIMARY KEY (id)
);

CREATE TABLE article_link (
  article1_id BIGINT,
  article2_id BIGINT
);

ALTER TABLE articles
  ADD CONSTRAINT fk_typeid FOREIGN KEY (typeid) REFERENCES types;

ALTER TABLE article_link
  ADD CONSTRAINT fk_article1 FOREIGN KEY (article1_id) REFERENCES articles;
ALTER TABLE article_link
  ADD CONSTRAINT fk_article2 FOREIGN KEY (article2_id) REFERENCES articles;
